[build]
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = "public"

[build.environment]
  NODE_VERSION = "14.18.0"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-gatsby" 